repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
    -   id: ruff
        args: [ --fix ]
-   repo: local
    hooks:
    -   id: mypy-type-check
        name: mypy
        entry: poetry run mypy .
        types: [ python ]
        pass_filenames: false
        language: python
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
